### ISSUE TITLE
Can't use onboard-mic AND mono speaker with `Codec_Zero_OnboardMIC_record_and_SPK_playback.state`

### ISSUE THREAD

**Issue by Sp0ngy** [iqaudio/Pi-Codec#7]
With loading the `Codec_Zero_Playback_only.state` via `sudo alsactl restore -f Codec_Zero_Playback_only.state` my Monospeaker works with this `speaker-test -t wav -c 1`. With this `.state` I can't record via the onboard-mic by doing `arecord -f cd test.wav`.

If I switch to `Codec_Zero_OnboardMIC_record_and_SPK_playback.state` via `sudo alsactl restore -f Codec_Zero_OnboardMIC_record_and_SPK_playback.state` I can record via `arecord -f cd test.wav`, but my monospeaker will not ouput with `aplay test.wav`. If I switch back to `Codec_Zero_Playback_only.state` I can play the `aplay test.wav` and it outputs on my monospeaker.

I assume that the `Codec_Zero_OnboardMIC_record_and_SPK_playback.state` uses the Stereo OUT, which unfortunatley I don't have hardware at my hand.

How can i configure the `.state` file to use onboard-mic and mono-out? Is this scenario covered by any `.state` file here?

**Comment by lurch** [comment]
That's the same `.state` file used by https://www.raspberrypi.com/documentation/accessories/audio.html#creating-a-toy-chatter-box and that definitely works with both the onboard microphone (for input) and mono speaker terminal (for output).
If I get a chance I'll double-check next week though :speaker: :microphone: 

In the meantime, you might want to experiment with changing the volume-levels of the different channels in `alsamixer` ?
See also https://github.com/raspberrypi/bookworm-feedback/issues/134 in case any of the comments there are useful.

**Comment by Sp0ngy** [comment]
@lurch: did you had any luck in reproducing the issue? I really cant figure out whats wrong here, playing with `alsamixer` even comparing the both .state files but no success.

**Comment by lurch** [comment]
Sorry, been too busy to take a look at this, and I doubt I'll get a chance to look at it until the new year.

**Comment by Sp0ngy** [comment]
I fixed it finally. I think the main issue was that the documentation for the .state files were really limited. At the end, it was this control, which needed to be set to true to enable the Onboard-Mic:
```
control.74 {
		iface MIXER
		name 'Mixin Left Mic 2 Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
```
As the filename `Codec_Zero_Playback_only.state` says, it is only Playback. But there is missing a configuration file for Playback (Mono OUT) and Onboard-Mic.
